"""
LinkedIn Profile API
---------------------
Accepts a LinkedIn profile URL and returns structured JSON.

No browser is used anywhere. Login happens once at startup by loading
session cookies from a real browser login (see app/linkedin_session.py).
Profile data is then fetched with a plain authenticated HTTP GET of the
profile page and parsed from its server-rendered HTML — see
app/voyager_client.py's module docstring for why this project ended up
here instead of the classic Voyager REST endpoint (which now 410s).

Responses are cached briefly (see app/cache.py) so repeated requests
for the same profile don't re-hit LinkedIn every time.

Interactive API docs are auto-generated by FastAPI at /docs.
"""

import os
import re
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import JSONResponse

from .linkedin_session import (
    LinkedInSession,
    AuthError,
    CheckpointError,
    RateLimitedError,
    ProfileNotFoundError,
)
from .voyager_client import HTMLProfileClient
from .cache import TTLCache

LINKEDIN_EMAIL = os.environ.get("LINKEDIN_EMAIL")
LINKEDIN_PASSWORD = os.environ.get("LINKEDIN_PASSWORD")
LI_AT_COOKIE = os.environ.get("LI_AT_COOKIE")
JSESSIONID = os.environ.get("JSESSIONID")
LINKEDIN_COOKIE_STRING = os.environ.get("LINKEDIN_COOKIE_STRING")
LINKEDIN_USER_AGENT = os.environ.get("LINKEDIN_USER_AGENT")
API_KEY = os.environ.get("API_KEY")
CACHE_TTL_SECONDS = int(os.environ.get("CACHE_TTL_SECONDS", "300"))

li_session: LinkedInSession | None = None
profile_client: HTMLProfileClient | None = None
cache = TTLCache(ttl_seconds=CACHE_TTL_SECONDS)


@asynccontextmanager
async def lifespan(app: FastAPI):
    global li_session, profile_client
    li_session = LinkedInSession(
        email=LINKEDIN_EMAIL,
        password=LINKEDIN_PASSWORD,
        li_at_cookie=LI_AT_COOKIE,
        jsessionid=JSESSIONID,
        cookie_string=LINKEDIN_COOKIE_STRING,
        user_agent=LINKEDIN_USER_AGENT,
    )
    li_session.login()
    profile_client = HTMLProfileClient(li_session)
    yield


app = FastAPI(
    title="LinkedIn Profile API",
    description="Returns structured JSON for a given LinkedIn profile URL, via direct HTTP requests (no browser).",
    version="0.4.0",
    lifespan=lifespan,
)

PROFILE_URL_RE = re.compile(r"^https?://(www\.)?linkedin\.com/in/([^/?#]+)/?$")


def extract_public_id(url: str) -> str:
    match = PROFILE_URL_RE.match(url)
    if not match:
        raise HTTPException(
            status_code=400,
            detail="Expected a LinkedIn profile URL like https://www.linkedin.com/in/username",
        )
    return match.group(2)


def check_api_key(x_api_key: str | None):
    if API_KEY and x_api_key != API_KEY:
        raise HTTPException(status_code=401, detail="Invalid or missing API key")


@app.get("/health")
async def health():
    return {
        "status": "ok",
        "logged_in": li_session is not None and li_session._authenticated,
        **cache.stats(),
    }


@app.get("/profile")
async def get_profile(
    url: str = Query(..., description="Full LinkedIn profile URL"),
    x_api_key: str | None = None,
):
    check_api_key(x_api_key)
    public_id = extract_public_id(url)

    cached = cache.get(public_id)
    if cached is not None:
        return JSONResponse(content={**cached, "_cache_hit": True})

    try:
        data = profile_client.fetch_profile(public_id, url)
        cache.set(public_id, data)
        return JSONResponse(content={**data, "_cache_hit": False})

    except ProfileNotFoundError as e:
        raise HTTPException(status_code=404, detail=str(e))
    except RateLimitedError as e:
        raise HTTPException(status_code=429, detail=str(e))
    except CheckpointError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except AuthError as e:
        raise HTTPException(status_code=502, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Fetch/parse failed: {str(e)}")
